<section class="main container" id="historia">
<div class="page-header">
  <h1><div class="block-title"><span class="deco"></span><span class="text">Reseña Histórica</span></div></h1>
  <h4>UNA BREVE RESEÑA HISTORICA DE LA CARRERA INTERNACIONAL SAN SILVESTRE “RAFAEL E. GUZMAN M.”
</h4>
  <p>Fundada en el año 1971 por Rafael E Guzmán Mendoza (1952-2012) en el tradicional y popular sector del Barrio Chiquinquira, Con una apuesta contra un joven del ejército que decían que era más veloz, la cual constaba de una carrera de ida y vuelta desde el barrio Chiquinquirá hasta el estadio Romélio Martínez cuya victoria le correspondió al joven Rafael Guzmán, ese duelo generó gran revuelo en el barrio y se pensó entonces en serio en la realización de una carrera organizada con toda las de ley; la primera competencia se dio el 16 de octubre de 1971 llevando como nombre Maratón Olímpica de Chiquinquirá en la cual resultó ganador el gestor de la competencia en un tiempo de 44 minutos con un recorrido de 12.5 km; Rafael E. Guzmán M. no volvió a competir puesto que se convirtió en director de dicha competencia dándole rienda suelta a su propósito de organizar una carrera atlética la misma que con el pasar de los años se convertiría en una prueba de porte internacional, pero él quería darle más a su Barranquilla del alma y pensó entonces en la realización de una carrera atlética que le diera la vuelta a la ciudad, a partir de la quinta edición, la prueba se llamó Carrera Nacional de Chiquinquira nombre que duraría 11 años hasta cuando quedó institucionalizada en 1982 como Carrera Internacional San Silvestre Barrio Chiquinquira partiendo y culminando en la iglesia de Chiquinquira teniendo como recorrido 15 kilómetros, con el pasar de los años la Carrera San Silvestre se convirtió en una tradición y toda una fiesta de fin de año, la cual fue liderada por su fundador hasta el 2011, dejando un gran legado deportivo que significo para su gestor un gran orgullo y satisfacción darle a <strong>BARRANQUILLA, COLOMBIA , LATINOAMERICA Y AL MUNDO ENTERO</strong>, este evento deportivo que marca el fin de toda actividad atlética  en Barranquilla  y demarca el camino de un nuevo año lleno de alegría no solo para los atletas participantes, sino también a todo  la familia atlética y deportiva, al igual que la alegría reflejada en la sonrisa y los aplausos de los habitantes de los diferentes barrios  populares de nuestra acogedora y pujante ciudad, que en unión a su familia salen a recibir a estos exponentes del deporte atlético a su paso.</p> <br>
  <p>Hoy con orgullo podemos decir que este año llegamos a la versión <strong>No 46</strong>, de estar haciéndose ininterrumpidamente, evento deportivo de talla internacional, y con mucho orgullo como barranquilleros y como Colombianos, podemos decir que la  <strong>CARRERA INTERNACIONAL SAN SILVESTRE FAFAEL E. GUZMAN M.</strong>,  es la carrera más antigua de venir desarrollándose en Colombia desde su creación hasta la presente y si la comparamos con otras carreras podemos concluir  que es la segunda carrera más antigua que ininterrumpidamente se realiza en Suramérica después de la Carrera de San Silvestre de Sao Paulo (Brasil  1925- 2016), y la cuarta a nivel de América, detrás de las carreras de Boston (E.U 1896- 2016), San Silvestre de Sao Paulo ( Brasil1925- 2016), Nueva York ( E.U 1970-2016) y Carrera Internacional San Silvestre “Rafal. E. Guzmán M” (Colombia 1971-2016), <strong>LA CARRERA INTERNACIONAL SAN SILVESTRE “RAFAEL E. GUZMAN M”</strong>  fue  declarado <strong>PATRIMONIO DE INTERES CULTURAL SOCIAL Y DEPORTIVO</strong> según acuerdo N° 0029 de 2013, Por el Honorable Concejo Distrital de Barranquilla; la cual es organizada por el Club de Atletismo Barrio Chiquinquirá y la Fundación Carrera Internacional San Silvestre.</p> <br>
  <p><b>En los siguientes link podrán ver la evolución del evento:</b></p>
  <ul>
    <li><a href="https://www.youtube.com/watch?v=307rqedhsaU" target="_blank">Comercial</li></a>
    <li><a href="https://www.youtube.com/watch?v=m1JnoH_d5xY" target="_blank">Bruchure</a></li>
    <li><a href="https://www.youtube.com/watch?v=o7EbWG5jJ7k" target="_blank">Historia del inicio</a></li>
    <li><a href="www.carrerasansilvestre.com" target="_blank">Página de la fundación</a></li>
  </ul>
  <br>
  <p>En virtud de lo anterior pasamos a solicitar su valioso apoyo en lo relacionado con el acompañamiento  de parte de ustedes y de esta manera divulgar este evento deportivo, que no solo involucra la práctica del deporte en su modalidad recreativa o competitiva, sino que también fomentamos la practica en los niños, jóvenes y adolescentes, mostrando nuestro compromiso  a la formación del ser humano integral y a su vez es un vehículo que sirve para mostrar la idiosincrasia del pueblo barranquillero, mostrando y promoviendo  una excelente imagen Cultural, Folclórica  y Deportiva de la ciudad.</p>
</div>

  <h1> <div class="block-title"><span class="deco"></span><span class="text">¿Sus organizadores quienes somos?</span></div></h1>
  <p><strong>El Club Deportivo De Atletismo Barrio Chiquinquirá</strong>, es una persona jurídica, cuya <strong>Personera Jurídica 00577</strong> de diciembre 14/ 82   y  NIT: 890.112.143-5, de derecho civil, de interés social, sin ánimo de lucro, que tiene por objeto social primordial, organizar y promover la Carrera Internacional San Silvestre que se realiza todos los 31 de Diciembre de cada año en el Distrito Especial Industrial y Portuario de Barranquilla.</p>

  <p>De igual manera la <strong>Fundación Carrera Internacional San Silvestre “Rafael E Guzmán M”, NIT: 900.720.348-1</strong>, la cual nace en el año 2012 en homenaje al deportista directivo Rafael Enrique Guzmán Mendoza (1952-2012).El cual llevo las banderas de tan majestuoso evento deportivo junto a su familia desde sus inicios.</p>

  <p>El <strong>Club Deportivo de Atletismo Barrio Chiquinquira</strong> en unión con la <strong>Fundación Carrera Internacional San Silvestre “Rafael E Guzmán M”</strong>, vienen fomentando la práctica deportiva del atletismo, la recreación y el aprovechamiento del tiempo libre a toda la población comenzando desde la niñez hasta terminar con el adulto mayor.</p>
</div>

   <p>La Carrera Internacional San Silvestre Rafael E. Guzman M., es la segunda carrera más antigua que ininterrumpidamente se realiza en Suramérica después de la carrera de San Silvestre de Brasil, y la cuarta a nivel de América, detrás de las carreras de Boston (E.U), San Silvestre de Sao Paulo ( Brasil), Nueva York ( E.U). Y a nivel mundial somos la 4ta, en antigüedad sin dejar de realizarla desde su creación, honor que muy pocas carreras en el mundo se pueden dar; razón por la cual hemos decidido que este evento deportivo se replique en los distintos departamentos de Colombia.</p>
  <div class="page-header">
  <blockquote class="pull-right">
  <p>“La profesión del corredor es una cuestión de herencia, de amor de la cual no se puede vivir”</p>
  <small><cite title="Nombre Apellidos">Rafael Enrique Guzmán Mendoza</cite></small>
</blockquote>
</div>
</section>